<?php

namespace Shevsky\Ecom\Enum;

class MailCategory
{
	const SIMPLE = 'SIMPLE';
	const ORDERED = 'ORDERED';
	const ORDINARY = 'ORDINARY';
	const WITH_DECLARED_VALUE = 'WITH_DECLARED_VALUE';
	const WITH_DECLARED_VALUE_AND_CASH_ON_DELIVERY = 'WITH_DECLARED_VALUE_AND_CASH_ON_DELIVERY';
	const WITH_DECLARED_VALUE_AND_COMPULSORY_PAYMENT = 'WITH_DECLARED_VALUE_AND_COMPULSORY_PAYMENT';
	const WITH_COMPULSORY_PAYMENT = 'WITH_COMPULSORY_PAYMENT';
}
